#cloud-config
package_update: true
package_upgrade: true

timezone: UTC

packages:
  - curl
  - wget
  - vim
  - htop
  - git
  - unzip
  - python3-pip
  - python3-venv
  - build-essential
  - libpq-dev
  - nodejs
  - npm
  - postgresql-client
  - certbot
  - python3-certbot-nginx

runcmd:
  - |
    ufw allow 22/tcp
    ufw allow 80/tcp
    ufw allow 443/tcp
    ufw --force enable
  - |
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    usermod -aG docker root
    curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
  - |
    apt-get install -y postgresql postgresql-contrib
    systemctl enable postgresql
    systemctl start postgresql
  - |
    apt-get install -y nginx
    systemctl enable nginx
    systemctl start nginx
